[package]
name = "rusty_volume"
version = "0.1.0"
edition = "2021"

[dependencies]
display-interface = "0.5.0"
embedded-graphics = "0.8.1"
gpio-cdev = "0.6.0"
linux-embedded-hal = "0.4.0"
rppal = "0.19.0"
ssd1306 = "0.9.0"
tokio = { version = "1.41.0", features = ["full", "process"] }
